from pyro.distributions import Normal
from torch import Tensor
from typing import Union
from .base import BaseProposal


class RandomWalk(BaseProposal):
    r"""
    Implements a random walk proposal, in which the candidate kernel is generated by
        .. math::
            \theta^* \sim \mathcal{N} \left (\theta, \sigma \right),

    where :math:`\theta` denotes the latest accepted parameter candidate, and :math:`\sigma` the scale of the
    distribution to use. Note that we generate the kernels on the constrained space of the parameters.
    """

    def __init__(self, scale: Union[float, Tensor] = 1e-2):
        """
        Initializes the :class:`RandomWalk` class.

        Args:
             scale: Optional parameter specifying the scale of the normal distribution. Can be either a "global" scale
                as specified by a ``float``, or a tensor with parameter specific scales.
        """

        super().__init__()
        self._scale = scale

    def build(self, context, state, filter_, y):
        return Normal(context.stack_parameters(constrained=False), self._scale).to_event(1)

    def exchange(self, latest, candidate, mask):
        latest.mean.masked_scatter_(mask, candidate.mean)
        latest.stddev.masked_scatter_(mask, candidate.stddev)
